services:
  lightrag:
    # container_name: lightrag
    # image: adeo-icarus-lightrag:25-12-2025
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - adeo-icarus-lightrag:25-12-2025
    # ports:
    #   - "${PORT:-9621}:9621"
    ports:
      - "8125:8000"
    volumes:
      # - ./data/rag_storage:/app/data/rag_storage
      # - ./data/inputs:/app/data/inputs
      # - ./config.ini:/app/config.ini
      - ./.env:/app/.env
    env_file:
      - .env
    restart: unless-stopped
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
